// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywxbsbgoipiwlwyrwlaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eGJzYmdvaXBpd2x3eXJ3bGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzkwNDQsImV4cCI6MjA2NjQxNTA0NH0.5JQiFsEkH5x-HJ-MohapVpxCIrlvvmAr02Dol6RkqxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);